RESEARCHER_FIRST_NAME : John
RESEARCHER_LAST_NAME  : Smith
RESEARCHER_CITATIONS  : /path/to/Smith/GoogleScholar_citations.csv
SUPERVISOR_FIRST_NAME : Jane
SUPERVISOR_LAST_NAME  : Doe
SUPERVISOR_CITATIONS  : /path/to/Doe/GoogleScholar_citations.csv
